//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Map_Bul_App.ResX {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Map_Bul_App.ResX.TextResource", typeof(TextResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string ActionBarFindPlaceholder {
            get {
                return ResourceManager.GetString("ActionBarFindPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding pin.
        /// </summary>
        internal static string AddingMarkerTitle {
            get {
                return ResourceManager.GetString("AddingMarkerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add pin.
        /// </summary>
        internal static string AddMarkerTitile {
            get {
                return ResourceManager.GetString("AddMarkerTitile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a photo.
        /// </summary>
        internal static string AddPinSelectPhoto {
            get {
                return ResourceManager.GetString("AddPinSelectPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a photo.
        /// </summary>
        internal static string AddPinTakePhoto {
            get {
                return ResourceManager.GetString("AddPinTakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open days.
        /// </summary>
        internal static string AddPinWorkDays {
            get {
                return ResourceManager.GetString("AddPinWorkDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open hours.
        /// </summary>
        internal static string AddPinWorkTime {
            get {
                return ResourceManager.GetString("AddPinWorkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event place.
        /// </summary>
        internal static string ArticleAdressLabelText {
            get {
                return ResourceManager.GetString("ArticleAdressLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        internal static string ArticleDateLabelText {
            get {
                return ResourceManager.GetString("ArticleDateLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        internal static string ArticlesButtonText {
            get {
                return ResourceManager.GetString("ArticlesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string AuthLogin {
            get {
                return ResourceManager.GetString("AuthLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string AuthPassword {
            get {
                return ResourceManager.GetString("AuthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string AuthRegistration {
            get {
                return ResourceManager.GetString("AuthRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string CalendarButtonText {
            get {
                return ResourceManager.GetString("CalendarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        internal static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditMarker {
            get {
                return ResourceManager.GetString("EditMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit pin.
        /// </summary>
        internal static string EditMarkerTitle {
            get {
                return ResourceManager.GetString("EditMarkerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address.
        /// </summary>
        internal static string EnterEmailAddressToast {
            get {
                return ResourceManager.GetString("EnterEmailAddressToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorToast {
            get {
                return ResourceManager.GetString("ErrorToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string EventTitleString {
            get {
                return ResourceManager.GetString("EventTitleString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EvryTime.
        /// </summary>
        internal static string EvryTime {
            get {
                return ResourceManager.GetString("EvryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show favorites pins.
        /// </summary>
        internal static string FavoriteMarkers {
            get {
                return ResourceManager.GetString("FavoriteMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        internal static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin filters.
        /// </summary>
        internal static string FilterAction {
            get {
                return ResourceManager.GetString("FilterAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        internal static string FilterCategory {
            get {
                return ResourceManager.GetString("FilterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string FilterFooterShow {
            get {
                return ResourceManager.GetString("FilterFooterShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only:.
        /// </summary>
        internal static string FilterSubCategory {
            get {
                return ResourceManager.GetString("FilterSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wi-fi.
        /// </summary>
        internal static string FilterWifi {
            get {
                return ResourceManager.GetString("FilterWifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open now.
        /// </summary>
        internal static string FilterWorkingNow {
            get {
                return ResourceManager.GetString("FilterWorkingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For review.
        /// </summary>
        internal static string ForReview {
            get {
                return ResourceManager.GetString("ForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string FSex {
            get {
                return ResourceManager.GetString("FSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        internal static string FutureEvents {
            get {
                return ResourceManager.GetString("FutureEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter as a guest.
        /// </summary>
        internal static string GuestLogin {
            get {
                return ResourceManager.GetString("GuestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local enter.
        /// </summary>
        internal static string LocalEntering {
            get {
                return ResourceManager.GetString("LocalEntering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string MSex {
            get {
                return ResourceManager.GetString("MSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My pin.
        /// </summary>
        internal static string MyPin {
            get {
                return ResourceManager.GetString("MyPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No favorite pins.
        /// </summary>
        internal static string NoFavoritePinsToast {
            get {
                return ResourceManager.GetString("NoFavoritePinsToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string NoInternetConnectionToast {
            get {
                return ResourceManager.GetString("NoInternetConnectionToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string OpenMapButton {
            get {
                return ResourceManager.GetString("OpenMapButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password sent to the specified e-mail.
        /// </summary>
        internal static string PasswordSentToast {
            get {
                return ResourceManager.GetString("PasswordSentToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        internal static string PastEvents {
            get {
                return ResourceManager.GetString("PastEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo: .
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin added.
        /// </summary>
        internal static string PinAddedToast {
            get {
                return ResourceManager.GetString("PinAddedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string PinBaseCategory {
            get {
                return ResourceManager.GetString("PinBaseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string PinDescription {
            get {
                return ResourceManager.GetString("PinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string PinDiscount {
            get {
                return ResourceManager.GetString("PinDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin edited.
        /// </summary>
        internal static string PinEditedToast {
            get {
                return ResourceManager.GetString("PinEditedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string PinEmail {
            get {
                return ResourceManager.GetString("PinEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preamble.
        /// </summary>
        internal static string PinIntroduction {
            get {
                return ResourceManager.GetString("PinIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string PinLogo {
            get {
                return ResourceManager.GetString("PinLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PinName {
            get {
                return ResourceManager.GetString("PinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PinPhone {
            get {
                return ResourceManager.GetString("PinPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string PinPhoto {
            get {
                return ResourceManager.GetString("PinPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WWW.
        /// </summary>
        internal static string PinSite {
            get {
                return ResourceManager.GetString("PinSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string PinStatus {
            get {
                return ResourceManager.GetString("PinStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string PinTags {
            get {
                return ResourceManager.GetString("PinTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string PinTicket {
            get {
                return ResourceManager.GetString("PinTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins.
        /// </summary>
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        internal static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore password.
        /// </summary>
        internal static string RecoverPasswordButton {
            get {
                return ResourceManager.GetString("RecoverPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password recovery.
        /// </summary>
        internal static string RecoverPasswordTitle {
            get {
                return ResourceManager.GetString("RecoverPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string RegistrationBirthDate {
            get {
                return ResourceManager.GetString("RegistrationBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegistrationButton {
            get {
                return ResourceManager.GetString("RegistrationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname*.
        /// </summary>
        internal static string RegistrationLastName {
            get {
                return ResourceManager.GetString("RegistrationLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail*.
        /// </summary>
        internal static string RegistrationLogin {
            get {
                return ResourceManager.GetString("RegistrationLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string RegistrationMiddleName {
            get {
                return ResourceManager.GetString("RegistrationMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name*.
        /// </summary>
        internal static string RegistrationName {
            get {
                return ResourceManager.GetString("RegistrationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string RegistrationPhone {
            get {
                return ResourceManager.GetString("RegistrationPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string RegistrationSex {
            get {
                return ResourceManager.GetString("RegistrationSex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server enter.
        /// </summary>
        internal static string ServerEntering {
            get {
                return ResourceManager.GetString("ServerEntering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all events.
        /// </summary>
        internal static string ShowAllEvents {
            get {
                return ResourceManager.GetString("ShowAllEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my pins.
        /// </summary>
        internal static string ShowMyMarker {
            get {
                return ResourceManager.GetString("ShowMyMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source link: .
        /// </summary>
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event start: .
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time:.
        /// </summary>
        internal static string StartTimeA {
            get {
                return ResourceManager.GetString("StartTimeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful registration, the password sent to the specified e-mail.
        /// </summary>
        internal static string SuccessfulRegistrationToast {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pin is added, wait for confirmation by the administrator..
        /// </summary>
        internal static string ThePinIsAddedToast {
            get {
                return ResourceManager.GetString("ThePinIsAddedToast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
