#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TK.CustomMap.Droid.Resource", IsApplication=false)]

namespace TK.CustomMap.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int border_shadow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int gradborder = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int ico_temple = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int info = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int monkey = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int pin = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int plus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int Rest_icon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public static int shadow_infowindow = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public static int xamarin = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050006
			public static int InfoTextTags = 2131034118;
			
			// aapt resource value: 0x7f050005
			public static int InfoTextTime = 2131034117;
			
			// aapt resource value: 0x7f050003
			public static int InfoTextType = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int InfoTextType2 = 2131034116;
			
			// aapt resource value: 0x7f050001
			public static int InfoWindowLayout = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int InfoWindowTitle = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int TitleImage = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int MapInfoWindowBordered = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int MapInfoWindowMy = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
